DO_BOX_URL = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
PRIVATE_KEY_PATH = "/Users/wielas/.ssh/id_rsa"
PUBLIC_KEY_PATH="/Users/wielas/.ssh/id_rsa.pub"
TOKEN = "dop_v1_adce7da7124fbd3544b28e494e148666ed8dac0c04205df571a820ca0893ea18"

Vagrant.configure("2") do |config|
  config.vm.define "minitwit1" do |droplet|
    droplet.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = PRIVATE_KEY_PATH
      override.vm.box = 'digital_ocean'
      override.vm.box_url = DO_BOX_URL
      override.nfs.functional = false
      override.droplet.ipv4_address = 146.190.207.33
      override.vm.allowed_synced_folder_types = :rsync
      provider.token = TOKEN
      provider.image = 'ubuntu-22-04-x64'
      provider.region = 'fra1'

    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk maven sqlite3 libsqlite3-dev tomcat9

    # Add public key to authorized_keys file
    mkdir -p /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    echo #{PUBLIC_KEY_PATH} >> /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R $USER:$USER /home/vagrant/.ssh
    SHELL

    end
  end
end