DO_BOX_URL = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
PRIVATE_KEY_PATH = "id_rsa"
TOKEN = "dop_v1_f5570d3e10b2f1e8a202b8a251c6719bef5fe8b36d28402f2813402567ae8396"

Vagrant.configure("2") do |config|
  config.vm.define "minitwit1" do |droplet|
    droplet.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = PRIVATE_KEY_PATH
      override.vm.box = 'digital_ocean'
      override.vm.box_url = DO_BOX_URL
      override.nfs.functional = false
      override.vm.allowed_synced_folder_types = :rsync
      provider.token = TOKEN
      provider.image = 'ubuntu-18-04-x64'
      provider.region = 'fra1'
    #   provider.size = '8gb'


    config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk maven sqlite3 libsqlite3-dev tomcat9
    SHELL
    end
  end
end