version: '3.5'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"  
    networks:
      - main

networks:
  main:
    name: itu-minitwit-network
