scrape_configs:
  - job_name: 'minitwit-prod'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
    - targets: ['172.17.0.1:8081']
      labels:
        application: 'minitwit-prod'

  - job_name: 'minitwit-dev'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:8082']
        labels:
          application: 'minitwit-dev'

  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['prometheus:9090']