scrape_configs:
  - job_name: 'minitwit'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'minitwit-prod'
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'minitwit-dev'
