name: Generate pdf report from LaTeX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'report/MSc_group_a.pdf'  # Prevent running the action when the PDF changes

jobs:
  generatepdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify Biber installation
        run: |
          docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull which biber

      - name: Generate PDF
        run: |
          docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull latexmk -pdf -shell-escape -outdir=/data/report -f /data/report/main.tex

      - name: Rename PDF
        run: |
          mv ./report/main.pdf ./report/MSc_group_a.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./report/MSc_group_a.pdf

  deploy_pdf:
    name: Deploy PDF
    needs: generatepdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download PDF
        uses: actions/download-artifact@v3
        with:
          name: report
          path: ./report/

      - name: Set up Git credentials
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin git@github.com:Academic-Weapons/ITU2023-DevOps.git
          git add report/MSc_group_a.pdf
          git commit -m "Add generated PDF"
          git push origin HEAD:dev --follow-tags
