name: Generate pdf report from LaTeX
on:
  push:
    branches:
      - report

jobs:
  generatepdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate PDF
        run: |
          docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull latexmk -pdf -shell-escape -outdir=/data/report /data/report/main.tex

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit PDF
        run: |
          git add report/main.pdf
          git diff --quiet && git diff --staged --quiet || git commit -m "Update PDF report"
          git push