---
name: Generate pdf report from LaTex
on:
  push:
    branches:
      - report2

  generatepdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create report directory
        run: mkdir -p report/build

      - name: Generate PDF
        run: |
          docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull latexmk -pdf -outdir=/data/report/build /data/report/main.tex

  deploy_pdf:
    name: Deploy PDF
    needs: generatepdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy PDF
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/build/main.pdf
