---
name: Generate pdf report from LaTex
on:
  push:
    branches:
      - report2

jobs:
  generatepdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate PDF
        run: |
          docker run --rm -i --user="$(id -u):$(id -g)" --net=none -v "$PWD":/data blang/latex:ctanfull latexmk -pdf -outdir=/data/report /data/report/main.tex

  deploy_pdf:
    name: Deploy PDF
    needs: generatepdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy PDF
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./report/main.pdf
